"""change log table

Revision ID: 1742c64c7e39
Revises: 65092c85c7a4
Create Date: 2024-10-06 00:45:11.712355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1742c64c7e39'
down_revision: Union[str, None] = '65092c85c7a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('log', 'url',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('log', 'method',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('log', 'process_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('log', 'response_code',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('log', 'user',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('log', 'user',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('log', 'response_code',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('log', 'process_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('log', 'method',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('log', 'url',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    # ### end Alembic commands ###
