"""change log table

Revision ID: 19d82bfb2fe8
Revises: 2d8bfa1a7df5
Create Date: 2024-10-05 23:54:38.254284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19d82bfb2fe8'
down_revision: Union[str, None] = '2d8bfa1a7df5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('url', sa.String(length=255), nullable=False))
    op.add_column('log', sa.Column('method', sa.Float(), nullable=True))
    op.add_column('log', sa.Column('process_time', sa.Float(), nullable=False))
    op.add_column('log', sa.Column('response_code', sa.Integer(), nullable=False))
    op.add_column('log', sa.Column('user', sa.String(length=255), nullable=False))
    op.drop_column('log', 'value')
    op.drop_column('log', 'message')
    op.drop_column('log', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('type', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.add_column('log', sa.Column('message', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('log', sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('log', 'user')
    op.drop_column('log', 'response_code')
    op.drop_column('log', 'process_time')
    op.drop_column('log', 'method')
    op.drop_column('log', 'url')
    # ### end Alembic commands ###
