"""change log table

Revision ID: 21874d9d2acb
Revises: 19d82bfb2fe8
Create Date: 2024-10-05 23:57:49.526338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21874d9d2acb'
down_revision: Union[str, None] = '19d82bfb2fe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('log', 'url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=False)
    op.alter_column('log', 'method',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=32),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('log', 'method',
               existing_type=sa.String(length=32),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('log', 'url',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
