"""change fk2

Revision ID: 3766174d702f
Revises: 173804f0f816
Create Date: 2024-09-30 20:17:06.149959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3766174d702f'
down_revision: Union[str, None] = '173804f0f816'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('price_supplier_id_fkey', 'price', type_='foreignkey')
    op.drop_constraint('price_product_id_fkey', 'price', type_='foreignkey')
    op.create_foreign_key(None, 'price', 'product_supplier', ['product_id', 'supplier_id'], ['product_id', 'supplier_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'price', type_='foreignkey')
    op.create_foreign_key('price_product_id_fkey', 'price', 'product', ['product_id'], ['id'])
    op.create_foreign_key('price_supplier_id_fkey', 'price', 'supplier', ['supplier_id'], ['id'])
    # ### end Alembic commands ###
