"""change log table

Revision ID: 65092c85c7a4
Revises: 21874d9d2acb
Create Date: 2024-10-06 00:24:25.073717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65092c85c7a4'
down_revision: Union[str, None] = '21874d9d2acb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('body', sa.String(length=4096), nullable=True))
    op.alter_column('log', 'method',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('log', 'method',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.drop_column('log', 'body')
    # ### end Alembic commands ###
