"""position and isTitle

Revision ID: 6e02587bbe8b
Revises: 162eceb7dfc0
Create Date: 2024-10-26 23:35:04.239562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e02587bbe8b'
down_revision: Union[str, None] = '162eceb7dfc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attribute', sa.Column('isTitle', sa.Boolean(), nullable=True))
    op.alter_column('attribute', 'unit_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('product_attribute', sa.Column('position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_attribute', 'position')
    op.alter_column('attribute', 'unit_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('attribute', 'isTitle')
    # ### end Alembic commands ###
