"""add auto increment to product_document and document_category

Revision ID: 7582b2c4c1bb
Revises: 61e1368de761
Create Date: 2024-11-02 20:46:40.603151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7582b2c4c1bb'
down_revision: Union[str, None] = '61e1368de761'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
