"""set isTitle is not nullable

Revision ID: 8657f82c00cc
Revises: 6e02587bbe8b
Create Date: 2024-10-26 23:39:31.740533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8657f82c00cc'
down_revision: Union[str, None] = '6e02587bbe8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attribute', 'isTitle',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attribute', 'isTitle',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
