"""add has_unit field to Attribute

Revision ID: a136d76c859e
Revises: 0b962c443c11
Create Date: 2024-10-30 16:18:47.192248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a136d76c859e'
down_revision: Union[str, None] = '0b962c443c11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attribute', sa.Column('hasUnit', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attribute', 'hasUnit')
    # ### end Alembic commands ###
