"""fix column name in attribute v2

Revision ID: aa955cc3c5cc
Revises: fb0e03f562d7
Create Date: 2024-10-30 16:21:31.968652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa955cc3c5cc'
down_revision: Union[str, None] = 'fb0e03f562d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attribute', sa.Column('is_title', sa.Boolean(), nullable=True))
    op.add_column('attribute', sa.Column('is_numeric', sa.Boolean(), nullable=True))
    op.add_column('attribute', sa.Column('has_unit', sa.Boolean(), nullable=True))
    op.drop_column('attribute', 'has_Unit')
    op.drop_column('attribute', 'is_Title')
    op.drop_column('attribute', 'is_Numeric')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attribute', sa.Column('is_Numeric', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('attribute', sa.Column('is_Title', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('attribute', sa.Column('has_Unit', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('attribute', 'has_unit')
    op.drop_column('attribute', 'is_numeric')
    op.drop_column('attribute', 'is_title')
    # ### end Alembic commands ###
