"""fix column name in attribute

Revision ID: fb0e03f562d7
Revises: a136d76c859e
Create Date: 2024-10-30 16:19:56.739376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb0e03f562d7'
down_revision: Union[str, None] = 'a136d76c859e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attribute', sa.Column('is_Title', sa.Boolean(), nullable=True))
    op.add_column('attribute', sa.Column('is_Numeric', sa.Boolean(), nullable=True))
    op.add_column('attribute', sa.Column('has_Unit', sa.Boolean(), nullable=True))
    op.drop_column('attribute', 'isNumeric')
    op.drop_column('attribute', 'isTitle')
    op.drop_column('attribute', 'hasUnit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attribute', sa.Column('hasUnit', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('attribute', sa.Column('isTitle', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('attribute', sa.Column('isNumeric', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('attribute', 'has_Unit')
    op.drop_column('attribute', 'is_Numeric')
    op.drop_column('attribute', 'is_Title')
    # ### end Alembic commands ###
